package com.smartspend.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseConnection {

    private static final String URL = "jdbc:h2:./data/smartspend;AUTO_SERVER=TRUE";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private DatabaseConnection() {
    }

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    public static void initializeDatabase() {
        String transactionTable =
            "CREATE TABLE IF NOT EXISTS transactions (" +
            "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "transaction_type VARCHAR(20) NOT NULL, " +
            "category VARCHAR(50) NOT NULL, " +
            "amount DECIMAL(12,2) NOT NULL, " +
            "description VARCHAR(255), " +
            "transaction_date DATE NOT NULL" +
            ")";

        String budgetTable =
            "CREATE TABLE IF NOT EXISTS budgets (" +
            "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "category VARCHAR(50) NOT NULL UNIQUE, " +
            "monthly_limit DECIMAL(12,2) NOT NULL" +
            ")";

        try (Connection connection = getConnection();
             Statement statement = connection.createStatement()) {

            statement.executeUpdate(transactionTable);
            statement.executeUpdate(budgetTable);

            System.out.println("Database connected and tables created successfully.");

        } catch (SQLException e) {
            System.out.println("DATABASE ERROR: " + e.getMessage());
            e.printStackTrace();
        }
    }
}